Added per route initcwnd/initrwnd option
canonical/netplan pull request #177
Opened 2020-12-07 19:22 UTC by n3wtype

## Description

Add possibility to set initcwnd/initrwnd options on routes.

## Checklist

- [ ] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).
- [ ] New/changed keys in YAML format are documented.
- [ ] \(Optional\) Adds example YAML for new feature.
- [ ] \(Optional\) Closes an open bug in Launchpad.

2020-12-09 07:57 UTC, slyon approved these changes
Thank you very much for your contribution!
This looks like a nice pull request, containing unit- and integration tests from the start. Nice work!

Before we get this merged, I'd like to see some smaller typo and formatting fixes (which I commented on inline), run it through the full integration testing suite and have someone else have another look at the schema changes for the new `initcwnd` and `initrwnd` settings – maybe @vorlonofportland ?

Otherwise this LGTM!

2020-12-09 07:57 UTC, slyon commented on doc/netplan.md
> +    ``initcwnd`` (scalar) – since ****
```suggestion
    ``initcwnd`` (scalar) – since **0.102**
```
This would most probably go into 0.102

2020-12-09 07:57 UTC, slyon commented on doc/netplan.md
> +           Must be a positive integer value.
```suggestion
          Must be a positive integer value.
```
Fix indentation.

2020-12-09 07:57 UTC, slyon commented on doc/netplan.md
> +    ``initrwnd`` (scalar) – since ****
```suggestion
    ``initrwnd`` (scalar) – since **0.102**
```
This would most probably go into 0.102.

2020-12-09 07:57 UTC, slyon commented on src/networkd.c
> +         g_string_append_printf(s, "InitialAdvertisedReceiveWindow=%u\n", r->initrwnd);
Please fix indentation of this block to 4 spaces (instead of 5).

2020-12-09 07:57 UTC, slyon commented on doc/netplan.md
> +
Please remove one of the empty lines.

2020-12-09 07:57 UTC, slyon commented on src/parse.c
> +    {"initrwnd", YAML_SCALAR_NODE, handle_routes_guint, NULL, route_offset(initrwnd)},
```suggestion
    {"initrwnd", YAML_SCALAR_NODE, handle_routes_guint, NULL, route_offset(initrwnd)},
```
Please fix trailing whitespace.

2020-12-09 07:57 UTC, slyon commented on doc/netplan.md
> +     :    The initrwnd to be used for the route, represented bynumber of segments.
```suggestion
     :    The initrwnd to be used for the route, represented by number of segments. 
```
Fix typo.

2020-12-09 07:57 UTC, slyon commented on doc/netplan.md
> +     :    The initcwnd to be used for the route, represented bynumber of segments.
```suggestion
     :    The initcwnd to be used for the route, represented by number of segments.
```
Fix typo.

2020-12-09 07:57 UTC, slyon commented on tests/integration/routing.py
> +            initcwnd: 16''' % {'r': self.backend, 'ec': self.dev_e_client})
Please fix indentation of `routes:` block.

2020-12-14 12:51 UTC, slyon approved these changes
Thanks a lot for your updates!
I ran the unit- & integration tests locally and can confirm everything is working as expected. This LGTM :eyes: now from a code & test perspective – Just one more tiny nitpick (whitespace formatting), which I commented inline.

Let's wait for the schema/naming review before we merge it.

2020-12-14 12:51 UTC, slyon commented on tests/integration/routing.py
> +         - 192.168.5.99/24
```suggestion
        - 192.168.5.99/24
```
Just a tiny nitpick I found on the 2nd look.

2021-02-17 19:29 UTC, cztk commented
Awesome work, thank you!
Came across this patch and can't wait to have this feature as dealing with netowrkd-dispatcher scripts doesn't work for me and would be a mess anyway.

2021-02-19 17:18 UTC, vorlonofportland requested changes

2021-02-19 17:18 UTC, vorlonofportland commented on doc/netplan.md
> +    ``initrwnd`` (scalar) – since **0.102**
Suggest naming this advertised-receive-window (same rationale).

2021-02-24 13:54 UTC, slyon commented
Thank you very much Steve for you recommendation wrt. the naming of the new options.
I've renamed the settings & variables accordingly and rebased the branch on top of current `master`.

This is now ready for merging.
Thank you very much @n3wtype for your contribution!

2021-02-24 13:55 UTC, merged