fix wrong filter for restart wpa units
canonical/netplan pull request #185
Opened 2021-01-24 16:24 UTC by Epsilond1

## Description

```
sudo netplan try
Job for netplan-wpa-wlan0.service canceled.

An error occurred: Command '['systemctl', 'stop', 'systemd-networkd.service', 'netplan-wpa-*.service']' returned non-zero exit status 1.
```

```
sudo systemctl stop netplan-wpa-*.service
zsh: no matches found: netplan-wpa-*.service
``` -- returned non-zero exit code.

`sudo systemctl stop netplan-wpa-wlan0.service` -- exit code is 0.

This PR fixed that problem. 

## Checklist

- [ ] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).
- [ ] New/changed keys in YAML format are documented.
- [ ] \(Optional\) Adds example YAML for new feature.
- [ ] \(Optional\) Closes an open bug in Launchpad.

2021-01-25 15:28 UTC, slyon requested changes
Hey @Epsilond1 thank you very much for contributing to Netplan and testing it in a ZSH environment.

The `zsh: no matches found` error seems to be a more generic problem, though, which we should not try to work around in netplan.

According to https://unix.stackexchange.com/questions/130958/scp-wildcard-not-working-in-zsh ZSH fails with this error if it cannot resolve the `netplan-wpa-*` glob, while bash passes it through as an argument to `systemctl`. Systemctl is correctly resolving the glob then.

So I think it would be better to make sure this parameter is passes through as an argument, instead of resolved by any shell. So I'd suggest to put the parameter in double-quotes instead of globbing via python, as there won't be an `netplan-wpa-IFACE.service` unit for each interface available in `/sys/class/net/`

Does this work for you?
```
systemctl stop "netplan-wpa-*.service"
```

If so, we should IMO add the double-quotes there, instead.

2021-01-25 15:28 UTC, slyon commented on netplan/cli/commands/apply.py
> +            wpa_services = ['netplan-wpa-{}.service'.format(iface) for iface in os.listdir('/sys/class/net/') if iface != 'lo']
```suggestion
            wpa_services = ['"netplan-wpa-*.service"']  # quote argument, so it won't be interpreted by the shell (zsh)
```

2021-01-25 17:02 UTC, Epsilond1 commented on netplan/cli/commands/apply.py
> +            wpa_services = ['netplan-wpa-{}.service'.format(iface) for iface in os.listdir('/sys/class/net/') if iface != 'lo']
Yes, it is really working way.

2021-01-26 10:21 UTC, slyon approved these changes
Thank you very much! This looks good to me.

Let me run it through a round of integration tests, to make sure it does not interfere with any other part of the system before merging.

2021-01-26 11:12 UTC, slyon requested changes
Unfortunately it doesn't seem to be that easy... Integration tests fail with:
```
Invalid unit name ""netplan-wpa-*.service"" escaped as "\x22netplan-wpa-*.service\x22" (maybe you should use systemd-escape?).
```

I think we need to find another way to pass through that parameter as a string, and avoid the shell/ZSH trying to expand the glob itself...

Cloud you have another look into that issue?

2024-06-26 10:52 UTC, slyon commented
Closing due to inactivity. Please re-open if somebody wants to pick up the work on this.

2024-06-26 10:52 UTC, closed without merging