Add additional bridge port settings
canonical/netplan pull request #410
Opened 2023-09-25 12:30 UTC by chdxD1

## Description
This MR adds additional bridge settings hairpin and learning on bridge ports.

This is my first MR to netplan, I tried my best to run the tests locally first.

## Checklist

- [x] Runs `make check` successfully. (except some nmcli local tests)
- [x] Retains 100% code coverage (`make check-coverage`).
- [x] New/changed keys in YAML format are documented. (but with version ???)
- [ ] \(Optional\) Adds example YAML for new feature.
- [ ] \(Optional\) Closes an open bug in Launchpad.

2023-09-25 12:37 UTC, chdxD1 commented
Also I am not sure regarding the ABI re-generate, it seems there are quite a lot of changes if done on this branch which are not related?

2023-09-28 14:18 UTC, daniloegea requested changes
Hi, thank you for your PR it's much appreciated.

I started reviewing it from the first commit but then realized you addresses most of the problems I pointed out and removed the `mcast-snooping` part in the last commit.

May I ask you to squash your commits and update the PR? It'll be easier to review.

Thanks again!

2023-10-06 09:54 UTC, chdxD1 commented
Yeah, mcast-snooping was a bit of a different topic (especially it needs to be default on, like STP), we will be using a systemd override for that internally for the time being.

Same goes for vlan_filtering on the bridge, I've seen the VLAN MR (#127) and it probably doesn't make sense to implement an option to *just* configure vlan_filtering without the backend actually configuring some. (We have this very specific case, backend just needs to set this flag, VLANs are then set by some K8s operator)

Anyway, I've squashed the trial/error commits (sorry for the additional lost review work there) and adjusted it according to the review comments :)

2023-11-01 20:00 UTC, daniloegea commented
Hi Christopher, sorry for the delay.

It's looking good. I created a couple of integration tests (and executed them with autopkgtest) using these two new options. Feel free to integrate them into your PR: https://github.com/daniloegea/netplan/commit/e543ddcecfef6e4167e2ca59acf12b1e71f17f25

As it's adding two new keys to Netplan, I'll ask @slyon what he thinks.

2023-11-14 11:06 UTC, chdxD1 commented
@daniloegea I finally found the time to add your commit, thank you for the test cases!

2023-12-06 10:47 UTC, slyon commented on doc/netplan-yaml.md
> +    > Define whether the bridge should use multicast sooping. The
The `mcast-snooping` logic was dropped from this PR.

2023-12-06 10:47 UTC, slyon commented on doc/netplan-yaml.md
> +    > default value is "true", which means that multicast snooping
The `mcast-snooping` logic was dropped from this PR.

2023-12-06 11:08 UTC, slyon commented on doc/netplan-yaml.md
> +  > unset, the kernel's default will be used.
todo: "When unset, the **backend's** default will be used."

(This is FALSE for NetworkManager, and the kernel's value for systemd-netword)

2023-12-06 11:12 UTC, slyon commented on src/parse.c
> +    {"learning", YAML_SCALAR_NODE, {.generic=handle_netdef_tristate}, netdef_offset(bridge_learning)}, \
```suggestion
    {"mac-learning", YAML_SCALAR_NODE, {.generic=handle_netdef_tristate}, netdef_offset(bridge_learning)}, \
```

todo: I feel like we should call this mac-learning, to stay in line with the corresponding VXLAN setting of similar functionality.

2023-12-06 11:25 UTC, slyon commented on src/networkd.c
> +        g_string_append_printf(params, "MulticastSnooping=%s\n", def->bridge_params.stp ? "true" : "false");
note: mcast_snooping has been dropped from this PR.

2023-12-06 12:01 UTC, slyon reviewed
Thank you @chdxD1 for your contribution to Netplan, and sorry for taking so long to comment.

I like the overall shape of this PR, thanks @daniloegea for your initial review! Those comments have been addressed already. Tests and CI are looking good, too! Thanks for adding/integrating unit- and integration tests.

I left some small inline-comments, mostly about documentation and naming of the new YAML schema.

We're introducing two new YAML settings here (let me try to confirm the schema with our architect):
* **hairpin** => We should **keep this as suggested**, IMO. "hairpin" is descriptive and common wording.
  * called "HairPin" in networkd
  * called "hairpin-mode" in NetworkManager
  * called "hairpin_mode" in iproute2
  * called "reflective relay" in Cisco/Juniper
* **learning** => We should **change this to "mac-learning"**, IMO. Just "learning" might be a bit too generic. Also, we should stay in-line with the "mac-learning" setting for VXLAN devices.
  * called "Learning" in systemd-networkd
  * Not generically implemented in NetworkManager (only for VXLAN)
  * called "learning" in iproute2
  * called "MAC Address Source-based Learning" in Cisco

The "learning" => "mac-learning" suggestion brings up one issue: What happens if a VXLAN device is used as the bridge-port? That way the new "mac-learning" setting would probably trump the VXLAN "mac-learning" setting and lead to unexpected behavior. You mention VXLAN tunnels in combination with FRR in your PR description. Could you please provide some more context on that? Would it be useful to actually re-use the VXLAN "mac-learning" setting and refactor it to become a generic setting. We could then write the "MacLearning=" setting in .netdev file and "Learning=" in .network file (for systemd-networkd), skipping the .netdev part on non-VXLAN ports. NetworkManager would not be affected, as it only supports the vxlan.learning setting (not on bridge-ports).

PS: rebasing your branch onto `origin/main` should fix the "RPM build (fedora:latest)" CI. The other failures are known false-positives.

2024-02-23 17:53 UTC, vorlonofportland approved these changes
These key names are straightforward and consistent with naming in upstream tooling, +1 for the schema changes.

2024-02-23 17:58 UTC, vorlonofportland commented
To be clear I'm ok with either 'learning' or 'port-mac-learning' as a name.

2024-02-26 10:56 UTC, slyon approved these changes
Thanks for the schema approval. Let's go with port-mac-learning then for my reasons given above.
I've rebased and pushed the corresponding renaming changes.

I think this should be ready for merging, just in time for the next Netplan release :)
This should cover some more cases for https://github.com/telekom/netplanner

2024-02-26 13:34 UTC, merged