docs: add a topic about security
canonical/netplan pull request #433
Opened 2024-01-10 17:38 UTC by daniloegea

## Description

## Checklist

- [ ] Runs `make check` successfully.
- [ ] Retains 100% code coverage (`make check-coverage`).
- [ ] New/changed keys in YAML format are documented.
- [ ] \(Optional\) Adds example YAML for new feature.
- [ ] \(Optional\) Closes an open bug in Launchpad.

2024-01-11 16:05 UTC, slyon approved these changes
Thank you, lgtm! (beside some small spelling nitpicks)

But I'd like to see @rkratky's sign-off on this, too.

2024-01-11 16:05 UTC, slyon commented on doc/.wordlist.txt
> +wifi
nitpick: Maybe this should be "Wi-Fi"? (cc @rkratky)

2024-01-11 16:05 UTC, slyon commented on doc/.wordlist.txt
> +Wireguard
nitpick: this should be "WireGuard"

2024-01-11 18:40 UTC, rkratky requested changes
@daniloegea Thank you for the addition of the topic. I left some comments and suggestions.

2024-01-11 18:40 UTC, rkratky commented on doc/security.md
> +discovered. See `dpkg-buildflags(1)` for details.
```suggestion
discovered. See the `dpkg-buildflags(1)` manual page for details.
```

2024-01-12 09:31 UTC, daniloegea commented on doc/security.md
> +of the configuration in YAML files. Netplan expects that all your YAML files
It's not a hard requirement. I guess something like `The recommended set of permissions is...` would be better.

2024-01-12 10:48 UTC, daniloegea commented
Thank you folks. I tried to address all the issues you have found. Please, let me know if there is anything else to improve.

2024-01-17 17:05 UTC, rkratky approved these changes

2024-01-17 17:07 UTC, merged